import './globals.css'

import Header from '@/widgets/header/header'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { Provider } from 'react-redux'
import ProviderNext from './provider'
import { store } from '@/stores/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'simplePokemonSite',
  description: 'Generated by ... whom?',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderNext>
          <Header />
          {children}
        </ProviderNext>
      </body>
    </html>
  )
}
